### ISSUE TITLE
'WeatherData' object has no attribute 'rain' and 'snow'

### ISSUE THREAD

**Issue by WRLPDZ** [bieniu/ha-meteo-imgw-pib#337]
### The problem

Hi, after update to 1.12.1 there are two errors.

AttributeError: 'WeatherData' object has no attribute 'rain'

AttributeError: 'WeatherData' object has no attribute 'snow'

### Home Assistant

2026.7.4

### Meteo IMGW-PIB integration

1.12.1

### Debug log

This error originated from a custom integration.

Rejestrator: custom_components.meteo_imgw_pib.coordinator
Źródło: helpers/update_coordinator.py:202
Integration: Meteo IMGW-PIB (dokumentacja, Problemy)
Pierwsze zdarzenie: 13:11:24 (1 wystąpienie)
Ostatnio zalogowany: 13:11:24

Unexpected error updating listener 140069471777280 for meteo_imgw_pib
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 202, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 667, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1213, in _async_write_ha_state
    ) = self.__async_calculate_state()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 604, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meteo_imgw_pib/sensor.py", line 193, in native_value
    return self.entity_description.value(self.coordinator.data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meteo_imgw_pib/sensor.py", line 134, in <lambda>
    value=lambda data: data.rain.value,
                       ^^^^^^^^^
AttributeError: 'WeatherData' object has no attribute 'rain'

This error originated from a custom integration.

Rejestrator: custom_components.meteo_imgw_pib.coordinator
Źródło: helpers/update_coordinator.py:202
Integration: Meteo IMGW-PIB (dokumentacja, Problemy)
Pierwsze zdarzenie: 13:11:24 (1 wystąpienie)
Ostatnio zalogowany: 13:11:24

Unexpected error updating listener 140069471778432 for meteo_imgw_pib
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 202, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 667, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1213, in _async_write_ha_state
    ) = self.__async_calculate_state()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 604, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meteo_imgw_pib/sensor.py", line 193, in native_value
    return self.entity_description.value(self.coordinator.data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meteo_imgw_pib/sensor.py", line 144, in <lambda>
    data.snow.value * 10 if data.snow.value is not None else None
                            ^^^^^^^^^
AttributeError: 'WeatherData' object has no attribute 'snow'

**Comment by bieniu** [comment]
Please update HA to version 2026.8.x and report back.
